name: registration
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  mysql_client: ^0.0.27
  cupertino_icons: ^1.0.8
  pdf: ^3.10.8
  printing: ^5.12.0
  file_picker: ^8.1.2
  excel: ^4.0.2
  archive: ^3.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/